export const GET_LIST_RATED_MOVIE = "GET_LIST_RATED_MOVIE";
export const GET_LIST_RATED_TV = "GET_LIST_RATED_TV";

export const GET_LIST_FAVORITE_MOVIE = "GET_LIST_FAVORITE_MOVIE";
export const GET_LIST_FAVORITE_TV = "GET_LIST_FAVORITE_TV";

export const GET_WATCH_LIST_MOVIE = "GET_WATCH_LIST_MOVIE";
export const GET_WATCH_LIST_TV = "GET_WATCH_LIST_TV";

export const GET_CREATED_LIST = "GET_CREATED_LIST";
export const GET_DETAILS_LIST = "GET_DETAILS_LIST";
export const GET_LIST_SEARCH = "GET_LIST_SEARCH";

export const CREATE_NEW_LIST = "CREATE_NEW_LIST";

export const DETELE_LIST_SEARCH = "DELE_LIST_SEARCH";

export const CHANGE_BACK_DROP_LIST = "CHANGE_BACK_DROP_LIST";

export const FETCH_REQUEST_DETAIL_LIST = "FETCH_REQUEST_DETAIL_LIST";
export const HIDE_REQUEST_DETAIL_LIST = "HIDE_REQUEST_DETAIL_LIST";

export const FETCH_REQUEST_CREATED_LIST = "FETCH_REQUEST_CREATED_LIST";
export const HIDE_REQUEST_CREATED_LIST = "HIDE_REQUEST_CREATED_LIST";

export const FETCH_REQUEST_RATED_MOVIE_LIST = "FETCH_REQUEST_RATED_MOVIE_LIST";
export const HIDE_REQUEST_RATED_MOVIE_LIST = "HIDE_REQUEST_RATED_MOVIE_LIST";

export const FETCH_REQUEST_RATED_TVSHOW_LIST =
  "FETCH_REQUEST_RATED_TVSHOW_LIST";
export const HIDE_REQUEST_RATED_TVSHOW_LIST = "HIDE_REQUEST_RATED_TVSHOW_LIST";
