export const GET_PHOTOS_MOVIE = "GET_PHOTOS_MOVIE";
export const GET_CREDIT_MOVIE = "GET_CREDIT";
export const GET_SIMILAR_MOVIE = "GET_SIMILAR_MOVIE";
export const GET_REVIEWS_MOVIE = "GET_REVIEWS_MOVIE";
export const GET_RECOMMEND_MOVIE = "GET_RECOMMEND_MOVIE";
export const GET_DETAIL_BANNER_MOVIE = "GET_DETAIL_BANNER_MOVIE";

export const GET_PHOTOS_TV_SHOW = "GET_PHOTOS_TV_SHOW";
export const GET_CREDIT_TV_SHOW = "GET_CREDIT";
export const GET_SIMILAR_TV_SHOW = "GET_SIMILAR_TV_SHOW";
export const GET_REVIEWS_TV_SHOW = "GET_REVIEWS_TV_SHOW";
export const GET_RECOMMEND_TV_SHOW = "GET_RECOMMEND_TV_SHOW";
export const GET_BANNER_TV_SHOW = "GET_BANNER_TV_SHOW";

// detail movie
export const FETCH_REQUEST_DETAIL_BANNER_MOVIE =
  "FETCH_REQUEST_DETAIL_BANNER_MOVIE";

export const HIDE_REQUEST_DETAIL_BANNER_MOVIE =
  "HIDE_REQUEST_DETAIL_BANNER_MOVIE";

export const FETCH_REQUEST_DETAIL_SIMILAR_MOVIE =
  "FETCH_REQUEST_DETAIL_SIMILAR_MOVIE";

export const HIDE_REQUEST_DETAIL_SIMILAR_MOVIE =
  "HIDE_REQUEST_DETAIL_SIMILAR_MOVIE";

export const FETCH_REQUEST_DETAIL_REVIEWS_MOVIE =
  "FETCH_REQUEST_DETAIL_REVIEWS_MOVIE";

export const HIDE_REQUEST_DETAIL_REVIEWS_MOVIE =
  "HIDE_REQUEST_DETAIL_REVIEWS_MOVIE";

export const FETCH_REQUEST_DETAIL_RECOMMEND_MOVIE =
  "FETCH_REQUEST_DETAIL_RECOMMEND_MOVIE";

export const HIDE_REQUEST_DETAIL_RECOMMEND_MOVIE =
  "HIDE_REQUEST_DETAIL_RECOMMEND_MOVIE";

// detail tvshow

export const FETCH_REQUEST_DETAIL_BANNER_TVSHOW =
  "FETCH_REQUEST_DETAIL_BANNER_TVSHOW";

export const HIDE_REQUEST_DETAIL_BANNER_TVSHOW =
  "HIDE_REQUEST_DETAIL_BANNER_TVSHOW";

export const FETCH_REQUEST_DETAIL_SIMILAR_TVSHOW =
  "FETCH_REQUEST_DETAIL_SIMILAR_TVSHOW";

export const HIDE_REQUEST_DETAIL_SIMILAR_TVSHOW =
  "HIDE_REQUEST_DETAIL_SIMILAR_TVSHOW";

export const FETCH_REQUEST_DETAIL_REVIEWS_TVSHOW =
  "FETCH_REQUEST_DETAIL_REVIEWS_TVSHOW";

export const HIDE_REQUEST_DETAIL_REVIEWS_TVSHOW =
  "HIDE_REQUEST_DETAIL_REVIEWS_TVSHOW";

export const FETCH_REQUEST_DETAIL_RECOMMEND_TVSHOW =
  "FETCH_REQUEST_DETAIL_RECOMMEND_TVSHOW";

export const HIDE_REQUEST_DETAIL_RECOMMEND_TVSHOW =
  "HIDE_REQUEST_DETAIL_RECOMMEND_TVSHOW";
