export const GET_LIST_MOVIE_POPULAR = "GET_LIST_MOVIE_POPULAR";
export const GET_LIST_MOVIE_TOP_RATED = "GET_LIST_MOVIE_TOP_RATED";
export const GET_LIST_MOVIE_NOW_PLAYING = "GET_LIST_MOVIE_NOW_PLAYING";
export const GET_LIST_MOVIE_UP_COMING = "GET_LIST_MOVIE_UP_COMING";
export const GET_TRAILER_MOVIE_POPULAR = "GET_TRAILER_MOVIE_POPULAR";

export const GET_MOVIE_LIST = "GET_MOVIE_LIST";

export const GET_GENRES_MOVIE_LIST = "GET_GENRES_MOVIE_LIST";
export const GET_GENRES_TV_SHOW_LIST = "GET_GENRES_TV_SHOW_LIST";

export const GET_TV_SHOW_TOP_RATE = "GET_TV_SHOW_TOP_RATE";
export const GET_TV_SHOW_LIST = "GET_TV_SHOW_LIST";

export const FETCH_REQUEST_MOVIE_POPULAR = "FETCH_REQUEST_MOVIE_POPULAR";
export const HIDE_REQUEST_MOVIE_POPULAR = "HIDE_REQUEST_MOVIE_POPULAR";

export const FETCH_REQUEST_MOVIE_TOP_RATED = "FETCH_REQUEST_MOVIE_TOP_RATED";
export const HIDE_REQUEST_MOVIE_TOP_RATED = "HIDE_REQUEST_MOVIE_TOP_RATED";

export const FETCH_REQUEST_TVSHOW_TOP_RATED = "FETCH_REQUEST_TVSHOW_TOP_RATED";
export const HIDE_REQUEST_TVSHOW_TOP_RATED = "HIDE_REQUEST_TVSHOW_TOP_RATED";
