export const GET_INFO_USER_ID = "GET_INFO_USER_ID";
export const GET_GUEST_SESSION = "GET_GUEST_SESSION";

export const FETCH_USER_LOADING = "FETCH_USER_LOADING";
export const HIDE_USER_LOADING = "HIDE_USER_LOADING";
